### ISSUE TITLE
package causes app crash on samsung smart tv

### ISSUE THREAD

**Issue by navid-yazdani** [ArteGEIE/videojs-vast#55]
Imported package in video player component, open player page and app crashed, there is no issue in new devices

Device:
 - OS: Tizen
 - Browser samsung browser
 - Version 2.4

Additional context:
I'm using video.js version 7.15.4

**Comment by Coralielm** [comment]
Hi @navid-yazdani,

Unfortunately, the package is not compatible with Tizen OS.

And we do not plan to support those TV platforms in the near future.
